apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../default

resources:
- auth_proxy_client_clusterrole.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_service.yaml

patchesStrategicMerge:
  - manager_auth_proxy_patch.yaml